### ISSUE TITLE
are you the owner of dedomil the j2me roms

### ISSUE THREAD

**Issue by dananothername** [dedomil/dedomil#1]

**Comment by yadavdotcodes** [comment]
Nope!, But I Am A Moderator At Dedomil Forum :)

**Comment by dedomil** [comment]
:)

**Comment by dananothername** [comment]
do you know tge owner

بتاريخ الجمعة، 21 أكتوبر 2022، جاء من Aditya Yadav ***@***.***

**Comment by dedomil** [comment]
Yes :)

**Comment by dananothername** [comment]
can zip all the jar in one and upload it in archives

بتاريخ الجمعة، 21 أكتوبر 2022، جاء من Aditya Yadav ***@***.***

**Comment by yadavdotcodes** [comment]
No! Do It Yourself :)
